# Generated by Django 5.2.5 on 2025-10-17 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectgroup_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='faculty_assignment',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='faculty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='core.projectgroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.projectgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.project'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.faculty'),
        ),
        migrations.DeleteModel(
            name='FacultyAssignment',
        ),
        migrations.DeleteModel(
            name='StudentAssignment',
        ),
    ]
