# Generated by Django 5.2.5 on 2025-10-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_project_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.faculty'),
        ),
    ]
