# Generated by Django 5.2.5 on 2025-10-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='core.projectgroup'),
        ),
        migrations.AlterField(
            model_name='project',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.projectgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.project'),
        ),
    ]
