# Generated by Django 5.2.5 on 2025-10-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_faculty_group_alter_project_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projectgroup'),
        ),
        migrations.AddField(
            model_name='application',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
