# Generated by Django 5.2.5 on 2025-12-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_student_faculty_alter_student_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dept_constraint',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
