# Generated by Django 5.2.5 on 2025-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_project_dept_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dept_constraint',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
